{% set name = "eralchemy" %}
{% set version = "1.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa66a3cd324abd27ad8e65908d7af48d8198c0c185aeb22189cf40516de25941

build:
  number: 0
  noarch: python
  entry_points:
    - eralchemy=eralchemy.main:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pygraphviz
    - python >=3.6
    - sqlalchemy <1.4

test:
  imports:
    - eralchemy
  commands:
    - pip check
    - eralchemy --help
  requires:
    - pip

about:
  home: https://github.com/Alexis-benoist/eralchemy
  summary: Simple entity relation (ER) diagrams generation
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - janjagusch
