schema_version: 1

context:
  name: eralchemy
  version: "1.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: fa66a3cd324abd27ad8e65908d7af48d8198c0c185aeb22189cf40516de25941

build:
  number: 3
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - eralchemy=eralchemy.main:cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - pygraphviz
    - python >=${{ python_min }}
    - sqlalchemy <1.4

tests:
  - python:
      imports:
        - eralchemy
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - eralchemy --help

about:
  summary: Simple entity relation (ER) diagrams generation
  license: Apache-2.0
  license_file: LICENSE.md
  homepage: https://github.com/Alexis-benoist/eralchemy

extra:
  recipe-maintainers:
    - janjagusch
