schema_version: 1

context:
  name: eralchemy
  version: "1.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8f82d329ec0cd9c04469adf36b8889b5ea2583e7e53c0fd2e784e176e1e27c7a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - eralchemy=eralchemy.main:cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - pygraphviz
    - python >=${{ python_min }}
    - sqlalchemy >=1.4.18

tests:
  - python:
      imports:
        - eralchemy
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - eralchemy --help

about:
  summary: Simple entity relation (ER) diagrams generation
  license: Apache-2.0
  license_file: LICENSE.md
  homepage: https://github.com/Alexis-benoist/eralchemy

extra:
  recipe-maintainers:
    - janjagusch
